name: data-analysis

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - pip=20.2.4
  - python=3.6.9
  - pip:
    - ipykernel==5.3.4
    - ipympl==0.5.8
    - ipython==7.16.1
    - lmfit==1.0.1
    - matplotlib==3.1.3
    - numpy==1.19.4
    - pandas==1.1.4
    - scipy==1.5.4
    - seaborn==0.11.0
    - jupyterlab_h5web[full]==0.0.8
