name: data-analysis

channels:
  - anaconda
  - conda-forge
  - defaults
  - rdkit

dependencies:
  - cython=0.29.21
  - pip=20.2.4
  - python=3.6.9
  - rdkit=2020.09.2
  - refnx=0.1.19
  - pip:
    - biopython==1.78
    - h5py==3.1.0
    - iminuit==1.5.4
    - ipykernel==5.3.4
    - ipympl==0.5.8
    - ipython==7.16.1
    - lmfit==1.0.1
    - matplotlib==3.1.3
    - numba==0.52.0
    - numexpr==2.7.1
    - numpy==1.19.4
    - pandas==1.1.4
    - PeakUtils==1.3.3
    - Pillow==8.0.1
    - PyYAML==5.3.1
    - requests==2.25.0
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - seaborn==0.11.0
    - statsmodels==0.12.1
    - sympy==1.7
    - ufit==1.4.4
    - jscatter==1.2.7.2
    - uncertainties==3.1.5
    - attrs==20.3.0
    - periodictable==1.5.3
    - jupyterlab_h5web[full]==0.0.8

